apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: skywatch-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: skywatch.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: skywatch-frontend
                port:
                  number: 5000
