frontend:
  image:
    repository: ghcr.io/hananva2-blip/skywatch-frontend
    tag: "51b25f0"
worker:
  image:
    repository: ghcr.io/hananva2-blip/skywatch-worker
    tag: "51b25f0"
rabbitmq:
  image: rabbitmq:3-management
